CREATE TABLE IF NOT EXISTS "servers" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  server_type INTEGER NOT NULL,
  server_version TEXT NOT NULL,
  status INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS "servers_permission" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES user(id) ON DELETE CASCADE,
  server_id INTEGER NOT NULL REFERENCES servers(id) ON DELETE CASCADE,
  permission INTEGER DEFAULT -1
);