PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS "user" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name text NOT NULL,
  username varchar(25) UNIQUE NOT NULL,
  permission INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "password" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER UNIQUE REFERENCES user (id) ON DELETE CASCADE,
  password text
);
