PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS "user" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  permission INTEGER DEFAULT -1
);
CREATE TABLE IF NOT EXISTS "password" (
  user_id INTEGER UNIQUE REFERENCES user (id) ON DELETE CASCADE,
  password TEXT NOT NULL
);