-- user
CREATE TABLE "user" (
  id INT PRIMARY KEY IDENTITY(1,1),
  username NVARCHAR(MAX) UNIQUE NOT NULL,
  "name" NVARCHAR(MAX) NOT NULL,
  email NVARCHAR(MAX) UNIQUE NOT NULL,
  create_at DATETIME2 DEFAULT CURRENT_TIMESTAMP,
  update_at DATETIME2 DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "password" (
  user INTEGER UNIQUE REFERENCES "user" (id) ON DELETE CASCADE,
  "password" NVARCHAR(MAX) NOT NULL,
  update_at DATETIME2 DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "cookie" (
  id INT PRIMARY KEY IDENTITY(1,1),
  user INTEGER REFERENCES "user" (id) ON DELETE CASCADE,
  cookie NVARCHAR(MAX) NOT NULL,
  create_at DATETIME2 DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "token" (
  id INT PRIMARY KEY IDENTITY(1,1),
  user INTEGER REFERENCES "user" (id) ON DELETE CASCADE,
  token NVARCHAR(MAX) NOT NULL,
  "permissions" NVARCHAR(MAX) NOT NULL,
  create_at DATETIME2 DEFAULT CURRENT_TIMESTAMP,
  update_at DATETIME2 DEFAULT CURRENT_TIMESTAMP
);
-- Server
CREATE TABLE "server" (
  id INT PRIMARY KEY IDENTITY(1,1),
  "owner" INTEGER REFERENCES "user" (id) ON DELETE CASCADE,
  "name" NVARCHAR(MAX) NOT NULL,
  software VARCHAR(128) NOT NULL,
  "version" NVARCHAR(MAX) NOT NULL,
  create_at DATETIME2 DEFAULT CURRENT_TIMESTAMP,
  update_at DATETIME2 DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "friends" (
  id INT PRIMARY KEY IDENTITY(1,1),
  server_id INTEGER REFERENCES "server" (id) ON DELETE CASCADE,
  "user_id" INTEGER REFERENCES "user" (id) ON DELETE CASCADE,
  "permissions" NVARCHAR(MAX) NOT NULL,
  UNIQUE(server_id, user_id)
);
CREATE TABLE "backups" (
  id INT PRIMARY KEY IDENTITY(1,1),
  server_id INTEGER REFERENCES "server" (id) ON DELETE CASCADE,
  uuid NVARCHAR(MAX) NOT NULL,
  software VARCHAR(128) NOT NULL,
  "version" NVARCHAR(MAX) NOT NULL,
  create_at DATETIME2 DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "runner" (
  id INT PRIMARY KEY IDENTITY(1,1),
  is_global BIT NOT NULL,
  is_local BIT NOT NULL,
  "user_id" INTEGER REFERENCES "user" (id) ON DELETE CASCADE
);
